apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.env }}
type: Opaque
data:
  # These values have been base64 encoded
  SECRET: c29tZV9yYW5kb21fc2VjcmV0X2lzX25vdF9hX3NlY3JldA==
  DATABASE_HOST: YnVja2V0ZGI=
  DATABASE_NAME: a2VueWE=
  DATABASE_USER: cGx1dG9fdXNlcg==
  DATABASE_PASSWORD: c2VjcmV0c2VjcmV0c2VjcmV0
  SSL_MODE: ZGlzYWJsZQ==
  DB_TYPE: cG9zdGdyZXM=
